//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class ChiTietHDNHDTO
    {
        [DataMember()]
        public String MaCTHDNH { get; set; }

        [DataMember()]
        public String MaHDNH { get; set; }

        [DataMember()]
        public String MaSP { get; set; }

        [DataMember()]
        public Int32 Gia { get; set; }

        [DataMember()]
        public Int32 SoLuong { get; set; }

        public ChiTietHDNHDTO()
        {
        }

        public ChiTietHDNHDTO(String maCTHDNH, String maHDNH, String maSP, Int32 gia, Int32 soLuong)
        {
			this.MaCTHDNH = maCTHDNH;
			this.MaHDNH = maHDNH;
			this.MaSP = maSP;
			this.Gia = gia;
			this.SoLuong = soLuong;
        }
    }
}
