//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HienNhiDTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHDBH
    {
        public string MaCTHDBH { get; set; }
        public string MaHDBH { get; set; }
        public string MaSP { get; set; }
        public short SoLuong { get; set; }
        public int GiaBan { get; set; }
    }
}
