//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HienNhiDTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSBH
    {
        public string MaCTSBH { get; set; }
        public string MaSBH { get; set; }
        public System.DateTime NgayTra { get; set; }
        public int ThanhTien { get; set; }
    }
}
