//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class GiaBanDTO
    {
        [DataMember()]
        public String MaGia { get; set; }

        [DataMember()]
        public String MaKH { get; set; }

        [DataMember()]
        public String MaSP { get; set; }

        [DataMember()]
        public Int32 Gia { get; set; }

        public GiaBanDTO()
        {
        }

        public GiaBanDTO(String maGia, String maKH, String maSP, Int32 gia)
        {
			this.MaGia = maGia;
			this.MaKH = maKH;
			this.MaSP = maSP;
			this.Gia = gia;
        }
    }
}
