//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class HoaDonNhapHangDTO
    {
        [DataMember()]
        public String MaHDNH { get; set; }

        [DataMember()]
        public String MaNCC { get; set; }

        [DataMember()]
        public Nullable<Int16> CKPhanTram { get; set; }

        [DataMember()]
        public Nullable<Int32> CKTienMat { get; set; }

        [DataMember()]
        public Int32 ThanhTien { get; set; }

        [DataMember()]
        public DateTime NgayLap { get; set; }

        public HoaDonNhapHangDTO()
        {
        }

        public HoaDonNhapHangDTO(String maHDNH, String maNCC, Nullable<Int16> cKPhanTram, Nullable<Int32> cKTienMat, Int32 thanhTien, DateTime ngayLap)
        {
			this.MaHDNH = maHDNH;
			this.MaNCC = maNCC;
			this.CKPhanTram = cKPhanTram;
			this.CKTienMat = cKTienMat;
			this.ThanhTien = thanhTien;
			this.NgayLap = ngayLap;
        }
    }
}
