//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HienNhiDTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBanHang
    {
        public string MaHDBH { get; set; }
        public string MaKH { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<short> CKPhanTram { get; set; }
        public Nullable<int> CKTienMat { get; set; }
        public int ThanhTien { get; set; }
    }
}
