//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class KhachHangDTO
    {
        [DataMember()]
        public String MaKH { get; set; }

        [DataMember()]
        public String TenKH { get; set; }

        [DataMember()]
        public String SoDT { get; set; }

        [DataMember()]
        public String DiaChi { get; set; }

        public KhachHangDTO()
        {
        }

        public KhachHangDTO(String maKH, String tenKH, String soDT, String diaChi)
        {
			this.MaKH = maKH;
			this.TenKH = tenKH;
			this.SoDT = soDT;
			this.DiaChi = diaChi;
        }
    }
}
