//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class LoaiSPDTO
    {
        [DataMember()]
        public String MaLoai { get; set; }

        [DataMember()]
        public String TenLoai { get; set; }

        public LoaiSPDTO()
        {
        }

        public LoaiSPDTO(String maLoai, String tenLoai)
        {
			this.MaLoai = maLoai;
			this.TenLoai = tenLoai;
        }
    }
}
