//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class NguoiDungDTO
    {
        [DataMember()]
        public String Username { get; set; }

        [DataMember()]
        public String Password { get; set; }

        [DataMember()]
        public Int16 Role { get; set; }

        public NguoiDungDTO()
        {
        }

        public NguoiDungDTO(String username, String password, Int16 role)
        {
			this.Username = username;
			this.Password = password;
			this.Role = role;
        }
    }
}
