//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class NhaCungCapDTO
    {
        [DataMember()]
        public String MaNCC { get; set; }

        [DataMember()]
        public String TenNCC { get; set; }

        [DataMember()]
        public String SoDT { get; set; }

        [DataMember()]
        public String DiaChi { get; set; }

        public NhaCungCapDTO()
        {
        }

        public NhaCungCapDTO(String maNCC, String tenNCC, String soDT, String diaChi)
        {
			this.MaNCC = maNCC;
			this.TenNCC = tenNCC;
			this.SoDT = soDT;
			this.DiaChi = diaChi;
        }
    }
}
