//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class SanPhamDTO
    {
        [DataMember()]
        public String MaLoai { get; set; }

        [DataMember()]
        public String MaSP { get; set; }

        [DataMember()]
        public String TenSP { get; set; }

        [DataMember()]
        public String MoTa { get; set; }

        [DataMember()]
        public String HinhAnh1 { get; set; }

        [DataMember()]
        public String HinhAnh2 { get; set; }

        [DataMember()]
        public String HinhAnh3 { get; set; }

        [DataMember()]
        public String HinhAnh4 { get; set; }

        [DataMember()]
        public Nullable<Int32> SoLuong { get; set; }

        [DataMember()]
        public String MaNCC { get; set; }

        [DataMember()]
        public Nullable<Int32> GiaVon { get; set; }

        public SanPhamDTO()
        {
        }

        public SanPhamDTO(String maLoai, String maSP, String tenSP, String moTa, String hinhAnh1, String hinhAnh2, String hinhAnh3, String hinhAnh4, Nullable<Int32> soLuong, String maNCC, Nullable<Int32> giaVon)
        {
			this.MaLoai = maLoai;
			this.MaSP = maSP;
			this.TenSP = tenSP;
			this.MoTa = moTa;
			this.HinhAnh1 = hinhAnh1;
			this.HinhAnh2 = hinhAnh2;
			this.HinhAnh3 = hinhAnh3;
			this.HinhAnh4 = hinhAnh4;
			this.SoLuong = soLuong;
			this.MaNCC = maNCC;
			this.GiaVon = giaVon;
        }
    }
}
