//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class SoBanHangDTO
    {
        [DataMember()]
        public String MaSBH { get; set; }

        [DataMember()]
        public DateTime NgayLap { get; set; }

        [DataMember()]
        public String MaKH { get; set; }

        [DataMember()]
        public Int32 TongDuNo { get; set; }

        [DataMember()]
        public Nullable<DateTime> NgayDongSo { get; set; }

        public SoBanHangDTO()
        {
        }

        public SoBanHangDTO(String maSBH, DateTime ngayLap, String maKH, Int32 tongDuNo, Nullable<DateTime> ngayDongSo)
        {
			this.MaSBH = maSBH;
			this.NgayLap = ngayLap;
			this.MaKH = maKH;
			this.TongDuNo = tongDuNo;
			this.NgayDongSo = ngayDongSo;
        }
    }
}
