//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/30 - 12:36:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HienNhiDTOs
{
    [DataContract()]
    public partial class SoChiTieuCuaHangDTO
    {
        [DataMember()]
        public String MaCT { get; set; }

        [DataMember()]
        public String LyDoChi { get; set; }

        [DataMember()]
        public DateTime NgayGio { get; set; }

        [DataMember()]
        public Int32 TongTien { get; set; }

        public SoChiTieuCuaHangDTO()
        {
        }

        public SoChiTieuCuaHangDTO(String maCT, String lyDoChi, DateTime ngayGio, Int32 tongTien)
        {
			this.MaCT = maCT;
			this.LyDoChi = lyDoChi;
			this.NgayGio = ngayGio;
			this.TongTien = tongTien;
        }
    }
}
