//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HienNhiDTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoChiTieuCuaHang
    {
        public string MaCT { get; set; }
        public string LyDoChi { get; set; }
        public System.DateTime NgayGio { get; set; }
        public int TongTien { get; set; }
    }
}
